### ISSUE TITLE
Transition to Grumpkin curve cycle

### ISSUE THREAD

**Issue by mpenciak** [lurk-lab/solidity-verifier#14]
This is a tracking issue to help transition the verifier from the Pasta curve cycle to the Grumpkin curve cycle.

## Regenerate data:
- `compressed-snark.json`, and `verifier-key.json` need to be regenerated from the `nova` repository.
- `neptune-constants-U24-{pallas, vesta}.json` need to be regenerated from the `neptune` repository.

## Library dependencies:
- `src/pasta/{Pallas, Vesta}.sol` will need to be replaced with BN254/Grumpkin
- The `poseidon-contract-gen.py` function should be modified to generate `src/poseidon/PoseidonNeptuneU24{BN254, Grumpkin}.sol`
- `Sponge.sol` should be modified accordingly

## Verifier contracts:
- `src/verifier/step1/Step1Data.sol`: will need to be re-generated from the python script, but the Logic can remain unchanged.
- `src/verifier/step2/*`: Modifications to use the new Grumpkin Neptune constants will need to be made in the Data and Logic files
- `src/verifier/step3/Step3Logic.sol`: Arithmetic will need to be changed from the Pallas/Vesta curve libraries to BN254/Grumpkin.
- `src/verifier/step4/*`: Arithmetic will need to be to be changed from the Pallas/Vesta curve libraries to BN254/Grumpkin.

This is just a sketch right now, so please feel free to edit this issue with more details.

**Comment by storojs72** [comment]
Started this work in https://github.com/lurk-lab/solidity-verifier/tree/grumpkin

**Comment by storojs72** [comment]
The transition implies: 1) adapting building blocks to a new curve cycle; 2) implementing verification steps (isolated parts of e2e verification flow) as a unit-tests using new curves; 3) wrapping all steps into the e2e contract, updating high-level abstractions and the loader.

Below is the list of building blocks required to be adapted (just to track progress of 1 stage):

- [ ] Bn256 / Grumpkin arithmetics
- [ ] Poseidon
- [ ] Sponge
- [ ] EqPolynomial
- [ ] IdentityPolynomial
- [ ] PolyEvalInstance
- [ ] SparsePolynomial
- [ ] KeccakTranscript
- [ ] Sumcheck

Next is list of verification steps:

- [ ] Step 1, 2
- [ ] Step 3
- [ ] Step 4, 5
- [ ] Step 6
- [ ] Step 7

**Comment by storojs72** [comment]
The grumpkin e2e contract is ready (obviously without final zeromorph-based step) - it lives in [grumpkin](https://github.com/lurk-lab/solidity-verifier/tree/grumpkin) branch. Further work implies careful merging it into main branch, which will be done in a "regular" basis - issuing set of correspondent PRs

**Comment by storojs72** [comment]
There is a decision made, to keep grumpkin contract in its own branch. The `main` branch is used as a source of fundamental cryptographic building blocks, so close the issue for now
